title = "Shashank welcomes You"
baseURL = "https://shashank.roy.gitlab.io/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
#resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Shashank Roy"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]

  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  font_size= 'm'
  text_color = "white"
  toc=true
  katex=true
  body_classes = "arial bg-white"
  post_content_classes="arial bg-white"
  show_reading_time=true
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/shashank.roy1997"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://www.instagram.com/shashankkroy/"
  youtube = ""
  github = "https://github.com/Mr-Markovian/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/shashankroy/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/tree_2.jpg"
  recent_posts_number = 3
  SidebarRecentLimit = 5

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
